CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 名
    first_name VARCHAR(50) NOT NULL,
    
    -- 名（フリガナ）
    first_name_kana VARCHAR(50) NOT NULL,
    
    -- 姓
    last_name VARCHAR(50) NOT NULL,
    
    -- 姓（フリガナ）
    last_name_kana VARCHAR(50) NOT NULL,
    
    -- メールアドレス: NULLを許可せず、一意性を保証
    email_address VARCHAR(255) NOT NULL UNIQUE,
    
    -- ステータス: 'active', 'inactive' など
    status VARCHAR(20) NOT NULL,
    
    -- 管理権限: 'admin', 'user' など
    authority VARCHAR(50) NOT NULL DEFAULT 'user',

    -- 登録日
    registration_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 初回ログイン完了フラグ
    is_first_login_completed BOOLEAN NOT NULL DEFAULT FALSE,

    -- 表示名
    display_name VARCHAR(100) UNIQUE,

    -- Stripe顧客ID
    stripe_customer_id VARCHAR(255),

    -- 最終ログイン日時
    last_login_at TIMESTAMP WITH TIME ZONE
);

-- インデックスの追加
CREATE INDEX idx_users_last_login_at ON users(last_login_at DESC);
CREATE INDEX idx_users_stripe_customer_id ON users(stripe_customer_id);