-- user_authentications テーブル (認証情報)
CREATE TABLE user_authentications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- usersテーブルの 'id' への参照 (外部キー)
    -- ON DELETE CASCADE: users の本体が削除されたら、認証情報も自動で削除する
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- 認証プロバイダ ('google', 'apple' など)
    provider      VARCHAR(50) NOT NULL,
    
    -- プロバイダが発行する一意のID (sub)
    provider_sub  VARCHAR(255) NOT NULL,
    
    -- プロバイダとsubの組み合わせは必ず一意にする
    UNIQUE (provider, provider_sub)
);